#!/bin/sh

set -e

if test "$1" = "configure"; then
    echo -n "Backing up any LVM2 metadata that may exist..."
    /sbin/vgcfgbackup >/dev/null 2>&1 || true
    echo "done."

    if test -f /etc/init.d/lvm2; then
        update-rc.d -f lvm2 remove >/dev/null 2>&1 || true
	rm -f /etc/init.d/lvm2
    fi

    if test -f /etc/init.d/lvm; then
        update-rc.d -f lvm remove >/dev/null 2>&1 || true
	rm -f /etc/init.d/lvm
    fi

    update-initramfs -u
fi

#DEBHELPER#
